title: becomebetter.in
description: "e.learning platform"
url: "https://angular.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
ga_property: "" # "UA-39010393-1"
permalink: /:categories/:slug/
repository_url: "https://github.com/symetics/becomebetter.in"
ws_course_id: 4

collections:
  pages:
    output: true
    permalink: /:name/
  categories:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "_pages" # an empty string here means all files in the project
    values:
      layout: "page"
  - scope:
      path: "_categories" # an empty string here means all files in the project
    values:
      layout: "category"
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      header_image: "header.jpg"
      toc: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/seite/:num/'
  title: ':title - Seite :num von :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
sass:
  style: :compressed
  sass_dir: assets/css
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - .gitignore
  - nginx.conf
  - cloudbuild.yaml
  - firebase-debug.log

# webrick:
#   headers:
#     Content-Security-Policy: "style-src 'self'"
